### ISSUE TITLE
vast ads with percentage timeOffset

### ISSUE THREAD

**Issue by theraw** [THEOplayer/docs-html5-sdk#23]
hello

currrently my vast ads preroll/midroll it's based on fixed time example
```js
        ads: [
            {
                sources: "https://***",
                timeOffset: 300
            },
            {
                sources: "https://***",
                timeOffset: 1500
            },
            {
                sources: "https://***",
                timeOffset: 5500
            },
            {
                sources: "https://***",
                timeOffset: "end"
            }
        ],
```
and i'm currently using this https://github.com/THEOplayer/docs-html5-sdk/tree/master/reference-apps/ui-visual-cues-midroll-ads

However this requires me to open each video and see if timeOffset it's ok with video duration 

what i would like to reach is

```js
        ads: [
            {
                sources: "https://***",
                timeOffset: "10%"
            },
            {
                sources: "https://***",
                timeOffset: "35%"
            },
            {
                sources: "https://***",
                timeOffset: "75%"
            },
            {
                sources: "https://***",
                timeOffset: "end"
            }
        ],
```

however it's not working 
![ds](https://user-images.githubusercontent.com/32969774/75091065-acf6bd80-5569-11ea-8269-0c69efdbe20c.png)

is there any chance to reach this? if not i would like to submit this as a feature request it's really helpfull if you want to use this player for/when you have too many videos!

**Comment by PooriaN** [comment]
Hi @theraw,
Thank you for your question, this function is definitely possible, you can check out this example:

**Comment by theraw** [comment]
hello @PooriaN 
i'm trying to look over demos but i can't find the one where is used a timeOffset with percentage, can you please tell me the name which one is it?!

**Comment by TimLeenaers** [comment]
Hi @theraw 
As @PooriaN already mentioned, it is possible to pass a percentage to `timeOffset`, just like you did in your example.
To show the visual cues, however, you should modify the `detectTimeOffset()` function from the `ui-visual-cues-midroll` example a bit (this currently only draws cues for seconds, 'start', and 'end'). This can be done in the following way:

```
function detectTimeOffset() {
        if (adsPresent) {
          var t = 0;
          console.log("duration: " + contentDuration);
          for (var ad of player.source.ads) {
            to[t] =
              ad.timeOffset == undefined
                ? 0
                : ad.timeOffset == "start"
                ? 0
                : isNaN(ad.timeOffset) && ad.timeOffset != "end"
                ? (parseFloat(ad.timeOffset.replace("%", "")) / 100) *
                  player.duration
                : ad.timeOffset;
            t++;
          }
        }
      }
```

**Comment by theraw** [comment]
@TimLeenaers that's working perfectly thank you
@PooriaN thank you
